require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BodyMassPercentilesController do

  # This should return the minimal set of attributes required to create a valid
  # BodyMassPercentile. As you add validations to BodyMassPercentile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all body_mass_percentiles as @body_mass_percentiles" do
      body_mass_percentile = BodyMassPercentile.create! valid_attributes
      get :index
      assigns(:body_mass_percentiles).should eq([body_mass_percentile])
    end
  end

  describe "GET show" do
    it "assigns the requested body_mass_percentile as @body_mass_percentile" do
      body_mass_percentile = BodyMassPercentile.create! valid_attributes
      get :show, :id => body_mass_percentile.id.to_s
      assigns(:body_mass_percentile).should eq(body_mass_percentile)
    end
  end

  describe "GET new" do
    it "assigns a new body_mass_percentile as @body_mass_percentile" do
      get :new
      assigns(:body_mass_percentile).should be_a_new(BodyMassPercentile)
    end
  end

  describe "GET edit" do
    it "assigns the requested body_mass_percentile as @body_mass_percentile" do
      body_mass_percentile = BodyMassPercentile.create! valid_attributes
      get :edit, :id => body_mass_percentile.id.to_s
      assigns(:body_mass_percentile).should eq(body_mass_percentile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BodyMassPercentile" do
        expect {
          post :create, :body_mass_percentile => valid_attributes
        }.to change(BodyMassPercentile, :count).by(1)
      end

      it "assigns a newly created body_mass_percentile as @body_mass_percentile" do
        post :create, :body_mass_percentile => valid_attributes
        assigns(:body_mass_percentile).should be_a(BodyMassPercentile)
        assigns(:body_mass_percentile).should be_persisted
      end

      it "redirects to the created body_mass_percentile" do
        post :create, :body_mass_percentile => valid_attributes
        response.should redirect_to(BodyMassPercentile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved body_mass_percentile as @body_mass_percentile" do
        # Trigger the behavior that occurs when invalid params are submitted
        BodyMassPercentile.any_instance.stub(:save).and_return(false)
        post :create, :body_mass_percentile => {}
        assigns(:body_mass_percentile).should be_a_new(BodyMassPercentile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BodyMassPercentile.any_instance.stub(:save).and_return(false)
        post :create, :body_mass_percentile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested body_mass_percentile" do
        body_mass_percentile = BodyMassPercentile.create! valid_attributes
        # Assuming there are no other body_mass_percentiles in the database, this
        # specifies that the BodyMassPercentile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BodyMassPercentile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => body_mass_percentile.id, :body_mass_percentile => {'these' => 'params'}
      end

      it "assigns the requested body_mass_percentile as @body_mass_percentile" do
        body_mass_percentile = BodyMassPercentile.create! valid_attributes
        put :update, :id => body_mass_percentile.id, :body_mass_percentile => valid_attributes
        assigns(:body_mass_percentile).should eq(body_mass_percentile)
      end

      it "redirects to the body_mass_percentile" do
        body_mass_percentile = BodyMassPercentile.create! valid_attributes
        put :update, :id => body_mass_percentile.id, :body_mass_percentile => valid_attributes
        response.should redirect_to(body_mass_percentile)
      end
    end

    describe "with invalid params" do
      it "assigns the body_mass_percentile as @body_mass_percentile" do
        body_mass_percentile = BodyMassPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BodyMassPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => body_mass_percentile.id.to_s, :body_mass_percentile => {}
        assigns(:body_mass_percentile).should eq(body_mass_percentile)
      end

      it "re-renders the 'edit' template" do
        body_mass_percentile = BodyMassPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BodyMassPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => body_mass_percentile.id.to_s, :body_mass_percentile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested body_mass_percentile" do
      body_mass_percentile = BodyMassPercentile.create! valid_attributes
      expect {
        delete :destroy, :id => body_mass_percentile.id.to_s
      }.to change(BodyMassPercentile, :count).by(-1)
    end

    it "redirects to the body_mass_percentiles list" do
      body_mass_percentile = BodyMassPercentile.create! valid_attributes
      delete :destroy, :id => body_mass_percentile.id.to_s
      response.should redirect_to(body_mass_percentiles_url)
    end
  end

end
