require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HeadCircumferencePercentilesController do

  # This should return the minimal set of attributes required to create a valid
  # HeadCircumferencePercentile. As you add validations to HeadCircumferencePercentile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all head_circumference_percentiles as @head_circumference_percentiles" do
      head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
      get :index
      assigns(:head_circumference_percentiles).should eq([head_circumference_percentile])
    end
  end

  describe "GET show" do
    it "assigns the requested head_circumference_percentile as @head_circumference_percentile" do
      head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
      get :show, :id => head_circumference_percentile.id.to_s
      assigns(:head_circumference_percentile).should eq(head_circumference_percentile)
    end
  end

  describe "GET new" do
    it "assigns a new head_circumference_percentile as @head_circumference_percentile" do
      get :new
      assigns(:head_circumference_percentile).should be_a_new(HeadCircumferencePercentile)
    end
  end

  describe "GET edit" do
    it "assigns the requested head_circumference_percentile as @head_circumference_percentile" do
      head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
      get :edit, :id => head_circumference_percentile.id.to_s
      assigns(:head_circumference_percentile).should eq(head_circumference_percentile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HeadCircumferencePercentile" do
        expect {
          post :create, :head_circumference_percentile => valid_attributes
        }.to change(HeadCircumferencePercentile, :count).by(1)
      end

      it "assigns a newly created head_circumference_percentile as @head_circumference_percentile" do
        post :create, :head_circumference_percentile => valid_attributes
        assigns(:head_circumference_percentile).should be_a(HeadCircumferencePercentile)
        assigns(:head_circumference_percentile).should be_persisted
      end

      it "redirects to the created head_circumference_percentile" do
        post :create, :head_circumference_percentile => valid_attributes
        response.should redirect_to(HeadCircumferencePercentile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved head_circumference_percentile as @head_circumference_percentile" do
        # Trigger the behavior that occurs when invalid params are submitted
        HeadCircumferencePercentile.any_instance.stub(:save).and_return(false)
        post :create, :head_circumference_percentile => {}
        assigns(:head_circumference_percentile).should be_a_new(HeadCircumferencePercentile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HeadCircumferencePercentile.any_instance.stub(:save).and_return(false)
        post :create, :head_circumference_percentile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested head_circumference_percentile" do
        head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
        # Assuming there are no other head_circumference_percentiles in the database, this
        # specifies that the HeadCircumferencePercentile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HeadCircumferencePercentile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => head_circumference_percentile.id, :head_circumference_percentile => {'these' => 'params'}
      end

      it "assigns the requested head_circumference_percentile as @head_circumference_percentile" do
        head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
        put :update, :id => head_circumference_percentile.id, :head_circumference_percentile => valid_attributes
        assigns(:head_circumference_percentile).should eq(head_circumference_percentile)
      end

      it "redirects to the head_circumference_percentile" do
        head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
        put :update, :id => head_circumference_percentile.id, :head_circumference_percentile => valid_attributes
        response.should redirect_to(head_circumference_percentile)
      end
    end

    describe "with invalid params" do
      it "assigns the head_circumference_percentile as @head_circumference_percentile" do
        head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HeadCircumferencePercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => head_circumference_percentile.id.to_s, :head_circumference_percentile => {}
        assigns(:head_circumference_percentile).should eq(head_circumference_percentile)
      end

      it "re-renders the 'edit' template" do
        head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HeadCircumferencePercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => head_circumference_percentile.id.to_s, :head_circumference_percentile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested head_circumference_percentile" do
      head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
      expect {
        delete :destroy, :id => head_circumference_percentile.id.to_s
      }.to change(HeadCircumferencePercentile, :count).by(-1)
    end

    it "redirects to the head_circumference_percentiles list" do
      head_circumference_percentile = HeadCircumferencePercentile.create! valid_attributes
      delete :destroy, :id => head_circumference_percentile.id.to_s
      response.should redirect_to(head_circumference_percentiles_url)
    end
  end

end
