require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HeightPercentilesController do

  # This should return the minimal set of attributes required to create a valid
  # HeightPercentile. As you add validations to HeightPercentile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all height_percentiles as @height_percentiles" do
      height_percentile = HeightPercentile.create! valid_attributes
      get :index
      assigns(:height_percentiles).should eq([height_percentile])
    end
  end

  describe "GET show" do
    it "assigns the requested height_percentile as @height_percentile" do
      height_percentile = HeightPercentile.create! valid_attributes
      get :show, :id => height_percentile.id.to_s
      assigns(:height_percentile).should eq(height_percentile)
    end
  end

  describe "GET new" do
    it "assigns a new height_percentile as @height_percentile" do
      get :new
      assigns(:height_percentile).should be_a_new(HeightPercentile)
    end
  end

  describe "GET edit" do
    it "assigns the requested height_percentile as @height_percentile" do
      height_percentile = HeightPercentile.create! valid_attributes
      get :edit, :id => height_percentile.id.to_s
      assigns(:height_percentile).should eq(height_percentile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HeightPercentile" do
        expect {
          post :create, :height_percentile => valid_attributes
        }.to change(HeightPercentile, :count).by(1)
      end

      it "assigns a newly created height_percentile as @height_percentile" do
        post :create, :height_percentile => valid_attributes
        assigns(:height_percentile).should be_a(HeightPercentile)
        assigns(:height_percentile).should be_persisted
      end

      it "redirects to the created height_percentile" do
        post :create, :height_percentile => valid_attributes
        response.should redirect_to(HeightPercentile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved height_percentile as @height_percentile" do
        # Trigger the behavior that occurs when invalid params are submitted
        HeightPercentile.any_instance.stub(:save).and_return(false)
        post :create, :height_percentile => {}
        assigns(:height_percentile).should be_a_new(HeightPercentile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HeightPercentile.any_instance.stub(:save).and_return(false)
        post :create, :height_percentile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested height_percentile" do
        height_percentile = HeightPercentile.create! valid_attributes
        # Assuming there are no other height_percentiles in the database, this
        # specifies that the HeightPercentile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HeightPercentile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => height_percentile.id, :height_percentile => {'these' => 'params'}
      end

      it "assigns the requested height_percentile as @height_percentile" do
        height_percentile = HeightPercentile.create! valid_attributes
        put :update, :id => height_percentile.id, :height_percentile => valid_attributes
        assigns(:height_percentile).should eq(height_percentile)
      end

      it "redirects to the height_percentile" do
        height_percentile = HeightPercentile.create! valid_attributes
        put :update, :id => height_percentile.id, :height_percentile => valid_attributes
        response.should redirect_to(height_percentile)
      end
    end

    describe "with invalid params" do
      it "assigns the height_percentile as @height_percentile" do
        height_percentile = HeightPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HeightPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => height_percentile.id.to_s, :height_percentile => {}
        assigns(:height_percentile).should eq(height_percentile)
      end

      it "re-renders the 'edit' template" do
        height_percentile = HeightPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HeightPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => height_percentile.id.to_s, :height_percentile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested height_percentile" do
      height_percentile = HeightPercentile.create! valid_attributes
      expect {
        delete :destroy, :id => height_percentile.id.to_s
      }.to change(HeightPercentile, :count).by(-1)
    end

    it "redirects to the height_percentiles list" do
      height_percentile = HeightPercentile.create! valid_attributes
      delete :destroy, :id => height_percentile.id.to_s
      response.should redirect_to(height_percentiles_url)
    end
  end

end
