require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeightPercentilesController do

  # This should return the minimal set of attributes required to create a valid
  # WeightPercentile. As you add validations to WeightPercentile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all weight_percentiles as @weight_percentiles" do
      weight_percentile = WeightPercentile.create! valid_attributes
      get :index
      assigns(:weight_percentiles).should eq([weight_percentile])
    end
  end

  describe "GET show" do
    it "assigns the requested weight_percentile as @weight_percentile" do
      weight_percentile = WeightPercentile.create! valid_attributes
      get :show, :id => weight_percentile.id.to_s
      assigns(:weight_percentile).should eq(weight_percentile)
    end
  end

  describe "GET new" do
    it "assigns a new weight_percentile as @weight_percentile" do
      get :new
      assigns(:weight_percentile).should be_a_new(WeightPercentile)
    end
  end

  describe "GET edit" do
    it "assigns the requested weight_percentile as @weight_percentile" do
      weight_percentile = WeightPercentile.create! valid_attributes
      get :edit, :id => weight_percentile.id.to_s
      assigns(:weight_percentile).should eq(weight_percentile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WeightPercentile" do
        expect {
          post :create, :weight_percentile => valid_attributes
        }.to change(WeightPercentile, :count).by(1)
      end

      it "assigns a newly created weight_percentile as @weight_percentile" do
        post :create, :weight_percentile => valid_attributes
        assigns(:weight_percentile).should be_a(WeightPercentile)
        assigns(:weight_percentile).should be_persisted
      end

      it "redirects to the created weight_percentile" do
        post :create, :weight_percentile => valid_attributes
        response.should redirect_to(WeightPercentile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weight_percentile as @weight_percentile" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeightPercentile.any_instance.stub(:save).and_return(false)
        post :create, :weight_percentile => {}
        assigns(:weight_percentile).should be_a_new(WeightPercentile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WeightPercentile.any_instance.stub(:save).and_return(false)
        post :create, :weight_percentile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weight_percentile" do
        weight_percentile = WeightPercentile.create! valid_attributes
        # Assuming there are no other weight_percentiles in the database, this
        # specifies that the WeightPercentile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WeightPercentile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => weight_percentile.id, :weight_percentile => {'these' => 'params'}
      end

      it "assigns the requested weight_percentile as @weight_percentile" do
        weight_percentile = WeightPercentile.create! valid_attributes
        put :update, :id => weight_percentile.id, :weight_percentile => valid_attributes
        assigns(:weight_percentile).should eq(weight_percentile)
      end

      it "redirects to the weight_percentile" do
        weight_percentile = WeightPercentile.create! valid_attributes
        put :update, :id => weight_percentile.id, :weight_percentile => valid_attributes
        response.should redirect_to(weight_percentile)
      end
    end

    describe "with invalid params" do
      it "assigns the weight_percentile as @weight_percentile" do
        weight_percentile = WeightPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeightPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => weight_percentile.id.to_s, :weight_percentile => {}
        assigns(:weight_percentile).should eq(weight_percentile)
      end

      it "re-renders the 'edit' template" do
        weight_percentile = WeightPercentile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WeightPercentile.any_instance.stub(:save).and_return(false)
        put :update, :id => weight_percentile.id.to_s, :weight_percentile => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weight_percentile" do
      weight_percentile = WeightPercentile.create! valid_attributes
      expect {
        delete :destroy, :id => weight_percentile.id.to_s
      }.to change(WeightPercentile, :count).by(-1)
    end

    it "redirects to the weight_percentiles list" do
      weight_percentile = WeightPercentile.create! valid_attributes
      delete :destroy, :id => weight_percentile.id.to_s
      response.should redirect_to(weight_percentiles_url)
    end
  end

end
